services:
  charts.charts_service:
    class: Drupal\charts\Services\ChartService
  charts.charts_attachment:
    class: Drupal\charts\Services\ChartAttachmentService
  charts.views_variable:
    class: Drupal\charts\Services\ViewsDataService
  charts.settings:
    class: Drupal\charts\Services\ChartsSettingsService
    arguments: ['@config.factory']
  plugin.manager.charts:
    class: Drupal\charts\ChartManager
    parent: default_plugin_manager
  plugin.manager.charts_type:
    class: Drupal\charts\TypeManager
    arguments: ['@module_handler', '@cache.discovery', '@event_dispatcher']
